Addition of overview page
goshencollege/gc-communicator pull request #15
Opened 2021-06-02 14:33 UTC by dboling19

# Description

Addition of overview page - Testing database pushing and pulling.,

## Fixes 

Please list any issues that are addressed by this change

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested Locally

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-02 17:12 UTC, davidwkdavidwk requested changes
This is a great start.  In addition to the comments I've already made I would like to see some tests to make sure that announcement creation is working as expected.  [https://symfony.com/doc/current/testing.html](https://symfony.com/doc/current/testing.html)

2021-06-02 17:12 UTC, davidwkdavidwk commented on templates/overview.html.twig
> +  </style>
Inline CSS is discouraged.  I'm going to let it slide here but I'm adding a new issue to implement better asset management to help with this kind of thing.

2021-06-03 01:12 UTC, davidwkdavidwk commented on templates/overview.html.twig
> +  </style>
Issue #16 created to address this

2021-06-03 20:30 UTC, dboling19 commented on .env.local
> +###< doctrine/doctrine-bundle ###
I thought I added that line already. I'll check again.

2021-06-03 21:57 UTC, dboling19 commented on templates/overview.html.twig
> +  <header>Communicator - Announcements</header>
I decided to just move this to a separate stylesheet.css file in the templates folder. This should allow me to customize a bit more CSS for the site(s) and keep things a bit neater overall.

2021-06-03 21:59 UTC, dboling19 commented on src/Controller/OverviewController.php
> +    $articleId = strval($article->getId());
You are right, but again I quickly tossed this in for demonstration purposes only to find that it didn't work after all. I'll just remove it for now, it won't be necessary for the final project at all.

Perhaps pulling the highest ID of the table might give me the results I was after, but ultimately it doesn't really matter in this case.

2021-06-08 19:56 UTC, davidwkdavidwk commented
Closing this PR because it was superseded by #21

2021-06-08 19:56 UTC, closed without merging