Feature/category add
goshencollege/gc-communicator pull request #33
Opened 2021-08-13 16:05 UTC by dboling19

# Description

Category selector has been added to the "new announcement" page, and the corresponding databases/tests have been updated to work with this change.

## Fixes 

Please list any issues that are addressed by this change

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-13 19:28 UTC, davidwkdavidwk requested changes
The relationship between the Category and Announcement entities needs to be fixed but, other than that, it looks good!

2021-08-13 19:28 UTC, davidwkdavidwk commented on src/Entity/Announcement.php
> +   * @ORM\Column(type="string", length=255)
The column type here *shouldn't* be string.  This should be a reference to a Category entity.  See line 31 as an example for creating relationships between entities.  You'll also need to edit the Category entity to reflect this change.

2021-08-13 19:28 UTC, davidwkdavidwk commented on src/Entity/Category.php
> +
There should be a field in here for `$announcements` and then getter and setter methods to get and add announcements to this category.

2021-08-16 18:05 UTC, davidwkdavidwk requested changes
One more change in the Category entity.  It's really close but it's easier to fix now than it would be down the road.

2021-08-16 18:05 UTC, davidwkdavidwk commented on src/Entity/Category.php
> +    }
You're really close here.  Checkout src/Entity/User.php lines 47 and 131-159.  You'll need to setup the `$this->announcement` attribute as an array and then add and remove announcements from that array in these getter and setter functions

2021-08-16 22:04 UTC, dboling19 commented
Unfinished - Waiting for update word

2021-08-17 18:38 UTC, davidwkdavidwk requested changes

2021-08-17 18:38 UTC, davidwkdavidwk commented on src/Entity/Category.php
> +    }
This is in the Category entity, if you're adding or removing an Announcement, you need to be passing in an Announcement for the argument, not a Category.  Does that make sense?

2021-08-17 18:38 UTC, davidwkdavidwk commented on src/Entity/Category.php
> +    public function getAnnouncement(): ?Announcement
This should really be named `getAnnouncements()` (ie. plural rather than singular)

2021-08-17 18:38 UTC, davidwkdavidwk commented on src/Entity/Category.php
> +    }
The `setAnnouncement` function can be removed since you have the add and remove functions below.

2021-08-17 18:38 UTC, davidwkdavidwk commented on src/Entity/Category.php
> +    }
Also checkout src/Entity/User.php line 47.  You need to init `$this->announements` in the constructor function.

2021-08-18 13:51 UTC, dboling19 commented
Meeting with David today to go over feature additions and gaining a better understanding of this process.

2021-08-18 14:10 UTC, davidwkdavidwk approved these changes

2021-08-18 14:10 UTC, merged